server:
  port: 8086

spring:
  datasource:
    url: jdbc:mariadb://100.88.187.37:3306/reactdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: totoro
    password: totoro
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    path: /home/totoro/Reactproject/chat-project/logs
  level:
    root: INFO
    com.example.chat: DEBUG